#!/bin/bash
set -e

# Distributed training script for Qwen3.5-4B on 2x g5.48xlarge (8x A10G 24GB each = 16 GPUs total)
# Usage:
#   On head node (instance 1):   ray start --head --port=6379
#   On worker node (instance 2): ray start --address=<head_private_ip>:6379
#   Then run this script only on the head node.

cd "$(dirname "$0")/.."
source /tmp/sky/bin/activate

# Locate CUDA_HOME
if [ -d "/usr/local/cuda" ] && [ -f "/usr/local/cuda/bin/nvcc" ]; then
  export CUDA_HOME=/usr/local/cuda
elif [ -f "/opt/pytorch/lib/python3.13/site-packages/nvidia/cu13/bin/nvcc" ]; then
  export CUDA_HOME=/opt/pytorch/lib/python3.13/site-packages/nvidia/cu13
else
  NVCC_PATH=$(which nvcc 2>/dev/null || true)
  if [ -n "$NVCC_PATH" ]; then
    export CUDA_HOME=$(dirname $(dirname "$NVCC_PATH"))
  else
    echo "ERROR: Could not find nvcc." >&2
    exit 1
  fi
fi
export PATH="$CUDA_HOME/bin:$PATH"
echo "Using CUDA_HOME=$CUDA_HOME"
rm -rf ~/.cache/flashinfer

# Verify Ray cluster has both nodes before starting
echo "Checking Ray cluster..."
ray status
TOTAL_GPUS=$(python3 -c "import ray; ray.init(address='auto'); resources = ray.available_resources(); print(int(resources.get('GPU', 0)))")
if [ "$TOTAL_GPUS" -lt 16 ]; then
  echo "ERROR: Expected 16 GPUs (2 nodes), found $TOTAL_GPUS. Make sure both nodes are in the Ray cluster."
  echo "On worker node run: ray start --address=<head_private_ip>:6379"
  exit 1
fi
echo "Ray cluster OK: $TOTAL_GPUS GPUs across 2 nodes."

# Download task directories
TASKS_DIR="/home/ec2-user/xin/harbor_tasks"
TASKS_DEDUPED_DIR="/home/ec2-user/xin/harbor_tasks/tasks_8192_deduped"

TASKS_COUNT=$(find "$TASKS_DEDUPED_DIR" -name 'instruction.md' 2>/dev/null | wc -l)
if [ "$TASKS_COUNT" -lt 10 ]; then
  echo "Downloading deduped 8192 tasks from S3 (found $TASKS_COUNT tasks, need more)..."
  mkdir -p "$TASKS_DEDUPED_DIR"
  aws s3 sync s3://endless-terminals-training/data/harbor_tasks_8192_deduped/ "$TASKS_DEDUPED_DIR/" --no-progress
else
  echo "Using existing deduped tasks ($TASKS_COUNT tasks)"
fi

# Download parquet (generated by prepare_data_deduped.sh)
DATA_DIR="/home/ec2-user/xin/data_harbor_qwen3_5_4b_g5_deduped"
mkdir -p "$DATA_DIR"
echo "Downloading deduped parquet from S3..."
aws s3 cp s3://endless-terminals-training/prepared_data/train_8192_deduped_4929tasks.parquet "$DATA_DIR/train.parquet"
aws s3 cp s3://endless-terminals-training/prepared_data/validation_8192_deduped_4929tasks.parquet "$DATA_DIR/validation.parquet"
echo "Parquet ready."

# Write task dir lists to JSON files — avoids "Argument list too long" on CLI
TRAIN_DIRS_FILE="/tmp/train_task_dirs.json"
VAL_DIRS_FILE="/tmp/val_task_dirs.json"
python3.13 -c "
import pandas as pd, json
df = pd.read_parquet('$DATA_DIR/train.parquet')
dirs = list(df['extra_info'].apply(lambda x: x['task_dir']).unique())
json.dump(dirs, open('$TRAIN_DIRS_FILE','w'))
print('Train tasks:', len(dirs))
"
python3.13 -c "
import pandas as pd, json
df = pd.read_parquet('$DATA_DIR/validation.parquet')
dirs = list(df['extra_info'].apply(lambda x: x['task_dir']).unique())
json.dump(dirs, open('$VAL_DIRS_FILE','w'))
print('Val tasks:', len(dirs))
"

# Checkpoint dirs
CKPT_DIR="/home/ec2-user/xin/checkpoints_harbor_qwen3_5_4b_g5_2node"
EXPORT_DIR="/home/ec2-user/xin/exports_harbor_qwen3_5_4b_g5_2node"
S3_CKPT="s3://endless-terminals-training/$(date +%Y%m%d)_8192deduped-task_harbor-grpo_qwen3.5-4b_g5-2node_Xsteps"

if [ -f "$CKPT_DIR/latest_ckpt_global_step.txt" ]; then
  RESUME_MODE=latest
  echo "Resuming from latest checkpoint."
else
  RESUME_MODE=null
  echo "Starting fresh."
fi

LOG_FILE="$CKPT_DIR/train_debug.log"
mkdir -p "$CKPT_DIR"
mkdir -p "$EXPORT_DIR"

# Background uploader: uploads checkpoints to S3 and deletes old ones from disk
(
  UPLOADED=""
  while true; do
    for step_dir in "$CKPT_DIR"/global_step_*/; do
      [ -d "$step_dir" ] || continue
      step=$(basename "$step_dir")
      if [ -f "$step_dir/trainer_state.pt" ] && ! echo "$UPLOADED" | grep -q "$step"; then
        echo "[uploader] Uploading $step to S3..."
        aws s3 sync "$step_dir" "$S3_CKPT/$step/" --no-progress --quiet
        latest=$(cat "$CKPT_DIR/latest_ckpt_global_step.txt" 2>/dev/null)
        if [ "$step" != "global_step_$latest" ]; then
          rm -rf "$step_dir"
          echo "[uploader] $step deleted from disk"
        else
          echo "[uploader] $step kept on disk (latest)"
        fi
        UPLOADED="$UPLOADED $step"
      fi
    done
    sleep 30
  done
) &
UPLOADER_PID=$!

# Background log syncer
(
  while true; do
    sleep 300
    aws s3 cp "$LOG_FILE" "$S3_CKPT/train_debug.log" --quiet 2>/dev/null
    aws s3 sync "$EXPORT_DIR/" "$S3_CKPT/evals/" --quiet 2>/dev/null
  done
) &
LOG_SYNC_PID=$!

# Background Docker cleaner: prune build cache every 30 minutes to prevent disk full
(
  while true; do
    sleep 1800
    docker builder prune -f --filter until=1h > /dev/null 2>&1
    docker image prune -f --filter until=2h > /dev/null 2>&1
    docker network prune -f > /dev/null 2>&1
  done
) &
DOCKER_CLEAN_PID=$!

# Run training
# 2x g5.48xlarge: 16x A10G 24GB total
# 4B model: tensor_parallel_size=8 per engine, 2 engines across 2 nodes
# A10G has 24GB — gpu_memory_utilization=0.55 leaves room for FSDP + activations
cd SkyRL
RAY_memory_usage_threshold=0.99 \
PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True \
HF_HOME=/tmp/hf_cache \
WANDB_MODE=offline \
SKYRL_DUMP_INFRA_LOG_TO_STDOUT=1 \
VLLM_ATTENTION_BACKEND=TORCH_SDPA \
VLLM_USE_FLASHINFER_SAMPLER=0 \
MSWEA_API_KEY=nokey \
NCCL_SOCKET_IFNAME=ens5 \
NCCL_IB_DISABLE=1 \
NCCL_SOCKET_FAMILY=AF_INET \
NCCL_DEBUG=WARN \
GLOO_SOCKET_IFNAME=ens5 \
python -m examples.train_integrations.harbor.entrypoints.main_harbor \
  "data.train_data=[\"$TRAIN_DIRS_FILE\"]" \
  "data.val_data=[\"$VAL_DIRS_FILE\"]" \
  trainer.policy.model.path=Qwen/Qwen3.5-4B \
  trainer.strategy=fsdp \
  trainer.algorithm.advantage_estimator=grpo \
  trainer.placement.colocate_all=true \
  trainer.placement.policy_num_gpus_per_node=8 \
  trainer.placement.policy_num_nodes=2 \
  trainer.placement.ref_num_gpus_per_node=8 \
  trainer.placement.ref_num_nodes=2 \
  trainer.flash_attn=false \
  trainer.use_sample_packing=false \
  trainer.policy.use_torch_compile=false \
  trainer.gradient_checkpointing=true \
  trainer.train_batch_size=8 \
  trainer.policy_mini_batch_size=8 \
  trainer.micro_forward_batch_size_per_gpu=1 \
  trainer.micro_train_batch_size_per_gpu=1 \
  trainer.max_prompt_length=2048 \
  trainer.algorithm.max_seq_len=4096 \
  trainer.epochs=1 \
  trainer.update_epochs_per_batch=2 \
  trainer.ckpt_interval=20 \
  trainer.eval_interval=20 \
  trainer.eval_batch_size=10 \
  trainer.eval_before_train=false \
  trainer.max_ckpts_to_keep=1 \
  trainer.logger=console \
  "trainer.project_name=simrl-sky-endless" \
  "trainer.run_name=endless-grpo-qwen3.5-4b-harbor-g5-2node" \
  "trainer.ckpt_path=$CKPT_DIR" \
  "trainer.export_path=$EXPORT_DIR" \
  trainer.resume_mode=$RESUME_MODE \
  generator.inference_engine.num_engines=2 \
  generator.inference_engine.http_endpoint_host=172.31.12.35 \
  generator.inference_engine.http_endpoint_port=8000 \
  generator.inference_engine.tensor_parallel_size=8 \
  generator.inference_engine.run_engines_locally=true \
  generator.inference_engine.backend=vllm \
  generator.inference_engine.weight_sync_backend=nccl \
  generator.inference_engine.async_engine=true \
  generator.inference_engine.enforce_eager=true \
  generator.inference_engine.gpu_memory_utilization=0.40 \
  generator.inference_engine.served_model_name=Qwen3.5-4B \
  generator.n_samples_per_prompt=4 \
  generator.max_turns=8 \
  generator.step_wise_trajectories=true \
  generator.merge_stepwise_output=true \
  "generator.sampling_params.max_generate_length=1024" \
  "generator.sampling_params.temperature=0.6" \
  2>&1 | tee "$LOG_FILE"
cd ..

kill $UPLOADER_PID 2>/dev/null
kill $LOG_SYNC_PID 2>/dev/null
kill $DOCKER_CLEAN_PID 2>/dev/null

echo "Uploading final log and evals to S3..."
aws s3 cp "$LOG_FILE" "$S3_CKPT/train_debug.log" --no-progress
aws s3 sync "$EXPORT_DIR/" "$S3_CKPT/evals/" --no-progress
echo "Training complete. All metrics uploaded to S3."
